# Generated by Django 5.0.3 on 2026-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Interlink Global College', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('max_testimonials', models.IntegerField(default=3, help_text='Maximum number of testimonials to show')),
                ('max_gallery_items', models.IntegerField(default=8, help_text='Maximum number of gallery items to show')),
                ('max_blog_posts', models.IntegerField(default=3, help_text='Maximum number of blog posts to show')),
                ('max_team_members', models.IntegerField(default=4, help_text='Maximum number of team members to show')),
                ('max_partners', models.IntegerField(default=6, help_text='Maximum number of partners to show')),
                ('stats', models.JSONField(default=list, help_text='[{"number": "1,200", "label": "Graduates"}, ...]')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_blog_posts', models.ManyToManyField(blank=True, related_name='homepage_featured', to='content.blogpost')),
                ('featured_gallery', models.ManyToManyField(blank=True, related_name='homepage_featured', to='content.galleryitem')),
                ('featured_partners', models.ManyToManyField(blank=True, related_name='homepage_featured', to='content.partner')),
                ('featured_team_members', models.ManyToManyField(blank=True, related_name='homepage_featured', to='content.teammember')),
                ('featured_testimonials', models.ManyToManyField(blank=True, related_name='homepage_featured', to='content.testimonial')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
